version: "3.11"
services:
  db_test:
    image: postgres:16.3
    env_file: ../../.env-test
    ports:
      - 3021:5432
    networks:
      - "dnd-test"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  back_app_test:
    build:
      context: ../../
      dockerfile: /ci-cd/test-proctoring/Dockerfile
    env_file:
      - ../../.env-test
    ports:
      - 3011:9000
    volumes:
      - ../../:/dnd
      - ../../.env-test:/dnd/.env
    networks:
      - "dnd-test"
    depends_on:
      - db_test
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    command: sh -c "alembic upgrade head && pytest -v tests/"

networks:
  dnd-test:
    name: "dnd-test"
