"""Changing tables to meet new requirements

Revision ID: 2025-11-04_changing_tables_to_meet_new_requirements
Revises: 2025_11_01_simplify_snapshot
Create Date: 2025-11-04 11:04:09.526531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025-11-04_changing_tables_to_meet_new_requirements'
down_revision: Union[str, None] = '2025_11_01_simplify_snapshot'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='NOW()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('proctoring', sa.Column('quiz_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        "proctoring_quiz_fk",
        "proctoring",
        "quiz",
        ["quiz_id"],
        ["id"],
    )

    op.add_column('proctoring', sa.Column('attempt_id', sa.Integer(), nullable=False))
    op.add_column('proctoring_type', sa.Column('default', sa.Boolean(), server_default='FALSE', nullable=False))

    op.drop_constraint('authorization_user_id_fkey', 'authorization', type_='foreignkey')
    op.drop_constraint('subject_user_user_id_fkey', 'subject_user', type_='foreignkey')
    op.drop_constraint('proctoring_user_id_fkey', 'proctoring', type_='foreignkey')

    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('authorization', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('proctoring', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('subject_user', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_foreign_key('authorization_user_id_fkey', 'authorization', 'user', ['user_id'], ['id'])
    op.create_foreign_key('subject_user_user_id_fkey', 'subject_user', 'user', ['user_id'], ['id'])
    op.create_foreign_key('proctoring_user_id_fkey', 'proctoring', 'user', ['user_id'], ['id'])
    op.execute("INSERT INTO role (name, rights_create, rights_read, rights_update, rights_delete) "
        "VALUES ('STUDENT', FALSE, FALSE, FALSE, FALSE)")



def downgrade() -> None:
    op.drop_constraint('proctoring_quiz_fk', 'proctoring', type_='foreignkey')

    op.drop_column('proctoring_type', 'default')
    op.drop_column('proctoring', 'attempt_id')
    op.drop_column('proctoring', 'quiz_id')
    op.drop_table('quiz')
    op.execute("DELETE FROM role WHERE name = 'STUDENT'")
