"""add_proctoring_tables

Revision ID: a285a269828e
Revises: 22756b6429d1
Create Date: 2025-03-04 13:39:04.718724

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a285a269828e"
down_revision: Union[str, None] = "22756b6429d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proctoring_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "absence_person", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("extra_person", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column(
            "person_substitution", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("looking_away", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column(
            "mouth_opening", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column(
            "hints_outside", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default="NOW()", nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default="NOW()", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proctoring",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default="NOW()", nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default="NOW()", nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["proctoring_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proctoring")
    op.drop_table("proctoring_type")
    # ### end Alembic commands ###
